/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "db": {
        "NOT_FOUND": string;
        "UNIQUE_VIOLATION": string;
        "FK_VIOLATION": string;
        "NOT_NULL_VIOLATION": string;
        "DEADLOCK": string;
        "LOCK_TIMEOUT": string;
        "CONNECTION_LOST": string;
        "INTERNAL_DRIVER_ERROR": string;
    };
    "entities": {
        "organization": {
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "CANNOT_PURGE_ACTIVE": string;
            "ALREADY_REVOKED": string;
            "ALREADY_ACTIVE": string;
        };
        "org-membership": {
            "CANNOT_SUSPEND": string;
            "CANNOT_ACTIVATE": string;
            "CANNOT_LEAVE": string;
            "CANNOT_BLOCK": string;
        };
        "project": {
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "CANNOT_PURGE_ACTIVE": string;
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
        };
        "department": {
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "CANNOT_PURGE_ACTIVE": string;
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
        };
        "team": {
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "CANNOT_PURGE_ACTIVE": string;
            "ALREADY_ARCHIVED": string;
            "ALREADY_ACTIVE": string;
        };
        "invite": {
            "CANNOT_ACCEPT_INACTIVE": string;
            "CANNOT_ACCEPT_EXPIRED": string;
            "CANNOT_DECLINE_INACTIVE": string;
            "CANNOT_DECLINE_EXPIRED": string;
            "CANNOT_CANCEL_INACTIVE": string;
            "CANNOT_CANCEL_EXPIRED": string;
            "CANNOT_INVALIDATE_INACTIVE": string;
            "CANNOT_INVALIDATE_EXPIRED": string;
            "CANNOT_EXPIRE_INACTIVE": string;
            "CANNOT_EXPIRE_UNDUE": string;
        };
        "project-account-assignment": {
            "ALREADY_REVOKED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
        };
        "dept-account-assignment": {
            "ALREADY_REVOKED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
        };
        "team-account-assignment": {
            "ALREADY_REVOKED": string;
            "ALREADY_ACTIVE": string;
            "CANNOT_PURGE_ACTIVE": string;
        };
    };
    "global": {
        "throttle": string;
    };
    "guard": {
        "permission": {
            "ACCOUNT_REQUIRED": string;
            "REALM_REQUIRED": string;
            "REALM_SCOPE_MISSING": string;
            "REALM_OUT_OF_SESSION_SCOPE": string;
            "GLOBAL_SCOPE_REQUIRES_DIRECT_LOGIN": string;
            "INSUFFICIENT_PERMISSIONS": string;
        };
        "authn": {
            "TOKEN_MISSING": string;
            "MALFORMED_AUTHORIZATION": string;
            "SESSION_REVOKED": string;
        };
        "reauthentication": {
            "REAUTHENTICATION_REQUIRED": string;
            "NOT_AUTHENTICATED": string;
        };
    };
    "services": {
        "kafka-retry": {
            "HANDLER_NOT_REGISTERED": string;
        };
        "kafka-incoming": {
            "EVENT_MISSING": string;
        };
        "jwt": {
            "INVALID_ACCESS_TOKEN": string;
        };
        "vault": {
            "REQUEST_FAILED": string;
            "INVALID_SIGNATURE": string;
        };
    };
    "validator": {
        "REQUIRED": string;
        "IS_OBJECT": string;
        "IS_STRING": string;
        "LENGTH": string;
        "MIN_LENGTH": string;
        "MAX_LENGTH": string;
        "ARRAY_MIN_SIZE": string;
        "ARRAY_MAX_SIZE": string;
        "MATCHES": string;
        "IS_EMAIL": string;
        "IS_UUID": string;
        "IS_PHONE": string;
        "IS_NUMBER": string;
        "IS_INT": string;
        "IS_POSITIVE": string;
        "MIN": string;
        "MAX": string;
        "IS_DECIMAL": string;
        "IS_BOOLEAN": string;
        "IS_DATE": string;
        "IS_ENUM": string;
        "IS_ARRAY": string;
        "ARRAY_UNIQUE": string;
        "NESTED": string;
        "IS_IN": string;
        "IS_ORDINAL": string;
        "NOT_EQUAL_TO": string;
        "IS_MS_STRING": string;
        "COMMON_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
